name: training
channels:
  - conda-forge
  - defaults
dependencies:
  - scikit-learn
  - jupyter_contrib_nbextensions
  - pyserial
  - numpy
  - numpy-stl
  - pandas
  - bqplot
  - ipywidgets
  - pythreejs
  - scikit-image
  - keras
  - tensorflow
  - blas==1.0=mkl
  - parso==0.7.0=py_0
  - termcolor==1.1.0=py_2
  - jupyter_client==6.1.6=py_0
  - prompt-toolkit==3.0.5=py_0
  - werkzeug==1.0.1=pyh9f0ad1d_0
  - wheel==0.34.2=py_1
  - pip==20.1.1=py_1
  - six==1.15.0=pyh9f0ad1d_0
  - absl-py==0.9.0=py37hc8dfbb8_1
  - pickleshare==0.7.5=py37_1001
  - backcall==0.2.0=py_0
  - python_abi==3.7=1_cp37m
  - ipython==7.16.1=py37h5ca1d4c_0
  - wcwidth==0.2.5=py_0
  - zipp==3.1.0=py_0
  - traitlets==4.3.3=py37_0
  - jupyter_core==4.6.3=py37_0
  - google-pasta==0.2.0=pyh8c360ce_0
  - certifi==2020.6.20=py37_0
  - ca-certificates==2020.6.24=0
  - pygments==2.6.1=py_0
  - python-dateutil==2.8.1=py_0
  - ipython_genutils==0.2.0=py37_0
  - keras-preprocessing==1.1.0=py_0
  - libblas==3.8.0=14_mkl
  - setuptools==49.2.0=py37hc8dfbb8_0
  - keras-applications==1.0.8=py_1
  - markdown==3.2.2=py_0
  - astor==0.8.1=pyh9f0ad1d_0
  - colorama==0.4.3=py_0
  - ipykernel==5.3.2=py37h5ca1d4c_0
  - liblapack==3.8.0=14_mkl
  - importlib-metadata==1.7.0=py37hc8dfbb8_0
  - libcblas==3.8.0=14_mkl
  - jedi==0.17.1=py37_0
  - gast==0.3.3=py_0
  - decorator==4.4.2=py_0
prefix: C:\SPB_Data\.conda\envs\training
